version: '3'

services:
  rabbitmq:
    image: rabbitmq:3-management
    hostname: dev-rabbit
    ports:
      - '127.0.0.1:5672:5672'
      - '127.0.0.1:15672:15672'
    networks: ['locale']

networks:
  locale:
